"""
Bedrock Guardrails validation wrapper — issue #16.

Every advisory generated by advisory_prompt.py must pass through validate_advisory()
before it is written to the audit log or sent via SNS. This is a non-negotiable
rule — see CLAUDE.md safety rules.

Guardrails are configured in the CDK safety stack (safety_stack.py) with:
  - Word blocks: false-certainty phrases ("you are safe", "no danger", etc.)
  - PII anonymization: phone numbers, addresses, names stripped from output
  - Content filters: hate, violence at MEDIUM+ strength

The guardrail ID is passed via WW_BEDROCK_GUARDRAIL_ID env var, set by CDK.
"""

import os
import boto3

REGION = os.environ.get("AWS_DEFAULT_REGION", "us-west-2")
GUARDRAIL_ID = os.environ.get("WW_BEDROCK_GUARDRAIL_ID", "")
GUARDRAIL_VERSION = "DRAFT"  # use DRAFT during development; pin to a version before launch


def validate_advisory(advisory_text: str, confidence: float = 1.0) -> dict:
    """Run advisory text through Bedrock Guardrails.

    Checks the advisory against:
      - Word blocks (false-certainty phrases)
      - PII filter (strips phone numbers, addresses, names)
      - Content policy (hate/violence filters)

    The confidence param is used for local pre-check only — the actual Guardrails
    evaluation is what matters for the audit record.

    Args:
        advisory_text: the SMS or brief text to validate
        confidence: the model's confidence score (used for local false-certainty pre-check)

    Returns:
        dict with:
          passed (bool)   — True if Guardrails action is NONE
          action (str)    — raw Guardrails action ("NONE" | "GUARDRAIL_INTERVENED")
          blocked_reason  — human-readable reason string if blocked, else None
          sanitized_text  — the text after PII anonymization (same as input if no PII)
    """
    if not GUARDRAIL_ID:
        # If the env var isn't set (local dev without CDK deployed), do a lightweight
        # local check only so development doesn't require live AWS resources.
        return _local_fallback_check(advisory_text, confidence)

    bedrock = boto3.client("bedrock-runtime", region_name=REGION)

    response = bedrock.apply_guardrail(
        guardrailIdentifier=GUARDRAIL_ID,
        guardrailVersion=GUARDRAIL_VERSION,
        source="OUTPUT",  # we're validating model output, not user input
        content=[{"text": {"text": advisory_text}}],
    )

    action = response.get("action", "NONE")
    passed = action == "NONE"

    # Extract the sanitized text (PII-scrubbed version if any was found).
    outputs = response.get("outputs", [])
    sanitized = outputs[0].get("text", advisory_text) if outputs else advisory_text

    blocked_reason = None
    if not passed:
        # Collect which policies triggered — useful for audit logging.
        assessments = response.get("assessments", [])
        reasons = []
        for assessment in assessments:
            for policy_type, policy_result in assessment.items():
                if isinstance(policy_result, dict) and policy_result.get("action") != "NONE":
                    reasons.append(f"{policy_type}: {policy_result.get('action')}")
        blocked_reason = "; ".join(reasons) if reasons else "blocked by guardrail"

    return {
        "passed": passed,
        "action": action,
        "blocked_reason": blocked_reason,
        "sanitized_text": sanitized,
    }


# Phrases that imply false certainty — blocked regardless of Guardrails availability.
# Keep this in sync with the word list in safety_stack.py.
FALSE_CERTAINTY_PHRASES = [
    "you are definitely safe",
    "you are safe",
    "no danger",
    "no risk",
    "all clear",
    "completely safe",
    "no threat",
    "nothing to worry",
]


def _local_fallback_check(advisory_text: str, confidence: float) -> dict:
    """Lightweight local check used when WW_BEDROCK_GUARDRAIL_ID is not set.

    Not a replacement for real Guardrails — only used for local dev/testing.
    Will warn loudly so it's never accidentally used in production.
    """
    import warnings
    warnings.warn(
        "WW_BEDROCK_GUARDRAIL_ID not set — using local fallback check only. "
        "This is NOT safe for production.",
        stacklevel=3,
    )

    text_lower = advisory_text.lower()
    for phrase in FALSE_CERTAINTY_PHRASES:
        if phrase in text_lower:
            return {
                "passed": False,
                "action": "GUARDRAIL_INTERVENED",
                "blocked_reason": f"false-certainty phrase detected: '{phrase}'",
                "sanitized_text": advisory_text,
            }

    return {
        "passed": True,
        "action": "NONE",
        "blocked_reason": None,
        "sanitized_text": advisory_text,
    }
